config/routes.rb
Dream::Application.routes.draw do
  resources :refreshes

  resources :apps

  resources :envs

  

end

app/models/app.rb
class App < ActiveRecord::Base
  validates :name, :description, :dev_lead, :env_support_lead, presence: true
  validates :name, uniqueness: true
end

app/models/env.rb
class Env < ActiveRecord::Base
  has_many :refreshes
  validates :name, :description, presence: true
  validates :name, uniqueness: true
end

app/models/refresh.rb
class Refresh < ActiveRecord::Base
  belongs_to :env
  validates :refresh_date, :refresh_type, :env_id, presence: true
  validates :env_id, uniqueness: { scope: :refresh_date,
    message: "should only be refreshed once per day"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render action: 'show', status: :created, location: @app }
      else
        format.html { render action: 'new' }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:name, :description, :dev_lead, :env_support_lead)
    end
end

app/controllers/envs_controller.rb
class EnvsController < ApplicationController
  before_action :set_env, only: [:show, :edit, :update, :destroy]

  # GET /envs
  # GET /envs.json
  def index
    @envs = Env.all
  end

  # GET /envs/1
  # GET /envs/1.json
  def show
  end

  # GET /envs/new
  def new
    @env = Env.new
  end

  # GET /envs/1/edit
  def edit
  end

  # POST /envs
  # POST /envs.json
  def create
    @env = Env.new(env_params)

    respond_to do |format|
      if @env.save
        format.html { redirect_to @env, notice: 'Env was successfully created.' }
        format.json { render action: 'show', status: :created, location: @env }
      else
        format.html { render action: 'new' }
        format.json { render json: @env.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /envs/1
  # PATCH/PUT /envs/1.json
  def update
    respond_to do |format|
      if @env.update(env_params)
        format.html { redirect_to @env, notice: 'Env was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @env.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /envs/1
  # DELETE /envs/1.json
  def destroy
    @env.destroy
    respond_to do |format|
      format.html { redirect_to envs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_env
      @env = Env.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def env_params
      params.require(:env).permit(:name, :description)
    end
end

app/controllers/refreshes_controller.rb
class RefreshesController < ApplicationController
  before_action :set_refresh, only: [:show, :edit, :update, :destroy]

  # GET /refreshes
  # GET /refreshes.json
  def index
    @refreshes = Refresh.all
  end

  # GET /refreshes/1
  # GET /refreshes/1.json
  def show
  end

  # GET /refreshes/new
  def new
    @refresh = Refresh.new
  end

  # GET /refreshes/1/edit
  def edit
  end

  # POST /refreshes
  # POST /refreshes.json
  def create
    @refresh = Refresh.new(refresh_params)

    respond_to do |format|
      if @refresh.save
        format.html { redirect_to @refresh, notice: 'Refresh was successfully created.' }
        format.json { render action: 'show', status: :created, location: @refresh }
      else
        format.html { render action: 'new' }
        format.json { render json: @refresh.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /refreshes/1
  # PATCH/PUT /refreshes/1.json
  def update
    respond_to do |format|
      if @refresh.update(refresh_params)
        format.html { redirect_to @refresh, notice: 'Refresh was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @refresh.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /refreshes/1
  # DELETE /refreshes/1.json
  def destroy
    @refresh.destroy
    respond_to do |format|
      format.html { redirect_to refreshes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_refresh
      @refresh = Refresh.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def refresh_params
      params.require(:refresh).permit(:refresh_date, :refresh_type, :env_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/envs_helper.rb
module EnvsHelper
end

app/helpers/refreshes_helper.rb
module RefreshesHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :dev_lead %><br>
    <%= f.text_field :dev_lead %>
  </div>
  <div class="field">
    <%= f.label :env_support_lead %><br>
    <%= f.text_field :env_support_lead %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Dev lead</th>
      <th>Env support lead</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= app.description %></td>
        <td><%= app.dev_lead %></td>
        <td><%= app.env_support_lead %></td>
        <td><%= link_to 'Show', app %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @app.description %>
</p>

<p>
  <strong>Dev lead:</strong>
  <%= @app.dev_lead %>
</p>

<p>
  <strong>Env support lead:</strong>
  <%= @app.env_support_lead %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/envs/_form.html.erb
<%= form_for(@env) do |f| %>
  <% if @env.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@env.errors.count, "error") %> prohibited this env from being saved:</h2>

      <ul>
      <% @env.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6, cols: 40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/envs/edit.html.erb
<h1>Editing env</h1>

<%= render 'form' %>

<%= link_to 'Show', @env %> |
<%= link_to 'Back', envs_path %>

app/views/envs/index.html.erb
<h1>Listing envs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @envs.each do |env| %>
      <tr>
        <td><%= env.name %></td>
        <td><%= env.description %></td>
        <td><%= link_to 'Show', env %></td>
        <td><%= link_to 'Edit', edit_env_path(env) %></td>
        <td><%= link_to 'Destroy', env, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Env', new_env_path %>

app/views/envs/new.html.erb
<h1>New Environment</h1>

<%= render 'form' %>

<%= link_to 'Back', envs_path %>

app/views/envs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @env.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @env.description %>
</p>

<%= link_to 'Edit', edit_env_path(@env) %> |
<%= link_to 'Back', envs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dream</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/refreshes/_form.html.erb
<%= form_for(@refresh) do |f| %>
  <% if @refresh.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@refresh.errors.count, "error") %> prohibited this refresh from being saved:</h2>

      <ul>
      <% @refresh.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :refresh_date %><br>
    <%= f.date_select :refresh_date %>
  </div>
  <div class="field">
    <%= f.label :refresh_type %><br>
    <%= f.text_field :refresh_type %>
  </div>
  <div class="field">
    <%= f.label :env_id %><br>
    <%= f.collection_select(:env_id, Env.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/refreshes/edit.html.erb
<h1>Editing refresh</h1>

<%= render 'form' %>

<%= link_to 'Show', @refresh %> |
<%= link_to 'Back', refreshes_path %>

app/views/refreshes/index.html.erb
<h1>Listing refreshes</h1>

<table>
  <thead>
    <tr>
      <th>Refresh date</th>
      <th>Refresh type</th>
      <th>Env</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @refreshes.each do |refresh| %>
      <tr>
        <td><%= refresh.refresh_date %></td>
        <td><%= refresh.refresh_type %></td>
        <td><%= refresh.env.name %></td>
        <td><%= link_to 'Show', refresh %></td>
        <td><%= link_to 'Edit', edit_refresh_path(refresh) %></td>
        <td><%= link_to 'Destroy', refresh, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Refresh', new_refresh_path %>

app/views/refreshes/new.html.erb
<h1>New refresh</h1>

<%= render 'form' %>

<%= link_to 'Back', refreshes_path %>

app/views/refreshes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Refresh date:</strong>
  <%= @refresh.refresh_date %>
</p>

<p>
  <strong>Refresh type:</strong>
  <%= @refresh.refresh_type %>
</p>

<p>
  <strong>Env:</strong>
  <%= @refresh.env.name %>
</p>

<%= link_to 'Edit', edit_refresh_path(@refresh) %> |
<%= link_to 'Back', refreshes_path %>